# import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

import = [
  "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[window]
padding = { x = 2, y = 2 }
dynamic_padding = true
option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
italic = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
offset = { x = 0, y = 0 }
size = 12

[env]
TERM = "xterm-256color"
